export const LAWMAKER_NAME_CLEANING = {
    // Standardizes various lawmaker name permutations presented in LAWS

    // 2019 
    'Ankney, Duane': 'Duane Ankney',
    'Fitzpatrick, Steve': 'Steve Fitzpatrick',
    'Malek, Sue': 'Sue Malek',
    'Sesso, Jon': 'Jon Sesso',
    'Sesso, Jon C.': 'Jon Sesso',
    'Jon C Sesso': 'Jon Sesso',
    'Barrett, Dick': 'Dick Barrett',
    'Flowers, Pat': 'Pat Flowers',
    'McClafferty, Edith': 'Edie McClafferty',
    'McClafferty, Edith (Edie)': 'Edie McClafferty',
    'Edith (Edie) McClafferty': 'Edie McClafferty',
    'McClafferty, Edith(Edie)': 'Edie McClafferty',
    'Edie Mcclafferty': 'Edie McClafferty',
    'Small, Jason': 'Jason Small',
    'Small, Jason D.': 'Jason Small',
    'Jason D Small': 'Jason Small',
    'Small, JasonD.': 'Jason Small',
    'Bennett, Bryce': 'Bryce Bennett',
    'Gauthier, Terry': 'Terry Gauthier',
    'McConnell, Nate': 'Nate McConnell',
    'Smith, Cary': 'Cary Smith',
    'Blasdel, Mark': 'Mark Blasdel',
    'Gillespie, Bruce': 'Bruce Gillespie',
    'McNally, Mary': 'Mary McNally',
    'Smith, Frank': 'Frank Smith',
    'Bogner, Kenneth': 'Kenneth Bogner',
    'Gross, Jen': 'Jen Gross',
    'Olszewski, Albert': 'Albert Olszewski',
    'Tempel, Russel': 'Russ Tempel',
    'Tempel, Russel (Russ)': 'Russ Tempel',
    'Russel (Russ) Tempel': 'Russ Tempel',
    'Tempel, Russel(Russ)': 'Russ Tempel',
    'Boland, Carlie': 'Carlie Boland',
    'Hinebauch, Steve': 'Steve Hinebauch',
    'Osmundson, Ryan': 'Ryan Osmundson',
    'Thomas, Fred': 'Fred Thomas',
    'Brown, Dee': 'Dee Brown',
    'Hoven, Brian': 'Brian Hoven',
    'Phillips, Mike': 'Mike Phillips',
    'Vance, Gordon': 'Gordon Vance',
    'Cohenour, Jill': 'Jill Cohenour',
    'Howard, David': 'David Howard',
    'Pomnichowski, JP': 'JP Pomnichowski',
    'Vuckovich, Gene': 'Gene Vuckovich',
    'Cuffe, Mike': 'Mike Cuffe',
    'Jacobson, Tom': 'Tom Jacobson',
    'Regier, Keith': 'Keith Regier',
    'Webb, Roger': 'Roger Webb',
    'Ellis, Janet': 'Janet Ellis',
    'Kary, Douglas': 'Doug Kary',
    'Kary, Douglas (Doug)': 'Doug Kary',
    'Douglas (Doug) Kary': 'Doug Kary',
    'Kary, Douglas(Doug)': 'Doug Kary',
    'Richmond, Tom': 'Tom Richmond',
    'Webber, Susan': 'Susan Webber',
    'Ellsworth, Jason': 'Jason Ellsworth',
    'Ellsworth, Jason W.': 'Jason Ellsworth',
    'Jason W Ellsworth': 'Jason Ellsworth',
    'Ellsworth, JasonW.': 'Jason Ellsworth',
    'llsworth, Jason': 'Jason Ellsworth',
    'Keenan, Bob': 'Bob Keenan',
    'Sales, Scott': 'Scott Sales',
    'Welborn, Jeffery': 'Jeff Welborn',
    'Welborn, Jeffrey W.': 'Jeff Welborn',
    'Jeffery W Welborn': 'Jeff Welborn',
    'Jeffrey W Welborn': 'Jeff Welborn',
    'Welborn, Jeffrey': 'Jeff Welborn',
    'Welborn, JeffreyW.': 'Jeff Welborn',
    'Esp, John': 'John Esp',
    'sp, John': 'John Esp',
    'Lang, Mike': 'Mike Lang',
    'Salomon, Daniel': 'Dan Salomon',
    'Salomon, Daniel R.': 'Dan Salomon',
    'Daniel R Salomon': 'Dan Salomon',
    'Salomon, DanielR.': 'Dan Salomon',
    'Fielder, Jennifer': 'Jennifer Fielder',
    'MacDonald, Margaret': 'Margie MacDonald',
    'MacDonald, Margaret (Margie)': 'Margie MacDonald',
    'Margaret (Margie) MacDonald': 'Margie MacDonald',
    'Sands, Diane': 'Diane Sands',
    'Abbott, Kim': 'Kim Abbott',
    'bbott, Kim': 'Kim Abbott',
    'Farris-Olsen, Robert': 'Robert Farris-Olsen',
    'Keogh, Connie': 'Connie Keogh',
    'Redfield, Alan': 'Alan Redfield',
    'Anderson, Fred': 'Fred Anderson',
    'Fern, Dave': 'Dave Fern',
    'Kerr-Carpenter, Emma': 'Emma Kerr-Carpenter',
    'Emma Kerr': 'Emma Kerr-Carpenter',
    'Regier, Matt': 'Matt Regier',
    'Bachmeier, Jacob': 'Jacob Bachmeier',
    'Fitzgerald, Ross': 'Ross Fitzgerald',
    'Fitzgerald, Ross H.': 'Ross Fitzgerald',
    'Ross H Fitzgerald': 'Ross Fitzgerald',
    'Fitzgerald, RossH.': 'Ross Fitzgerald',
    'Knudsen, Rhonda': 'Rhonda Knudsen',
    'Ricci, Vince': 'Vince Ricci',
    'Bahr, Jade': 'Jade Bahr',
    'Fleming, Frank': 'Frank Fleming',
    'Knudsen, Casey': 'Casey Knudsen',
    'Running Wolf, Tyson': 'Tyson Running Wolf',
    'Runningwolf, Tyson T.': 'Tyson Running Wolf',
    'Tyson T Running Wolf': 'Tyson Running Wolf',
    'Running Wolf, Tyson T.': 'Tyson Running Wolf',
    'RunningWolf, TysonT.': 'Tyson Running Wolf',
    'RunningWolf, Tyson': 'Tyson Running Wolf',
    'Ballance, Nancy': 'Nancy Ballance',
    'Fuller, John': 'John Fuller',
    'Krautter, Joel': 'Joel Krautter',
    'Krautter, Joel G.': 'Joel Krautter',
    'Joel G Krautter': 'Joel Krautter',
    'Ryan, Marilyn': 'Marilyn Ryan',
    'Bartel, Dan': 'Dan Bartel',
    'Funk, Moffie': 'Moffie Funk',
    'Krotkov, Jasmine': 'Jasmine Krotkov',
    'Sales, Walt': 'Walt Sales',
    'Beard, Becky': 'Becky Beard',
    'Galt, Wylie': 'Wylie Galt',
    'Lenz, Dennis': 'Dennis Lenz',
    'Lenz, Dennis R.': 'Dennis Lenz',
    'Dennis R Lenz': 'Dennis Lenz',
    'Lenz, DennisR.': 'Dennis Lenz',
    'Schreiner, Casey': 'Casey Schreiner',
    'Bedey, David': 'David Bedey',
    'Garcia, Rodney': 'Rodney Garcia',
    'Loge, Denley': 'Denley Loge',
    'Loge, Denley M.': 'Denley Loge',
    'Denley M Loge': 'Denley Loge',
    'Loge, DenleyM.': 'Denley Loge',
    'Shaw, Ray': 'Ray Shaw',
    'Shaw, Ray L.': 'Ray Shaw',
    'Ray L Shaw': 'Ray Shaw',
    'Berglee, Seth': 'Seth Berglee',
    'Garner, Frank': 'Frank Garner',
    'Lynch, Ryan': 'Ryan Lynch',
    'Sheldon-Galloway, Lola': 'Lola Sheldon-Galloway',
    'Galloway, Lola': 'Lola Sheldon-Galloway',
    'Lola Sheldon': 'Lola Sheldon-Galloway',
    'Bessette, Barbara': 'Barbara Bessette',
    'Glimm, Carl': 'Carl Glimm',
    'Mandeville, Forrest': 'Forrest Mandeville',
    'Skees, Derek': 'Derek Skees',
    'Bishop, Laurie': 'Laurie Bishop',
    'Greef, Sharon': 'Sharon Greef',
    'Manzella, Theresa': 'Theresa Manzella',
    'Smith, Bridget': 'Bridget Smith',
    'Brown, Bob': 'Bob Brown',
    'Grubbs, Bruce': 'Bruce Grubbs',
    'Marler, Marilyn': 'Marilyn Marler',
    'Stewart Peregoy, Sharon': 'Sharon Stewart Peregoy',
    'StewartPeregoy, Sharon': 'Sharon Stewart Peregoy',
    'Brown, Zach': 'Zach Brown',
    'Gunderson, Steve': 'Steve Gunderson',
    'McKamey, Wendy': 'Wendy McKamey',
    'Sullivan, Katie': 'Katie Sullivan',
    'Burnett, Tom': 'Tom Burnett',
    'Hamilton, Jim': 'Jim Hamilton',
    'Mercer, Bill': 'Bill Mercer',
    'Sweeney, Mark': 'Mark Sweeney',
    'Buttrey, Edward': 'Ed Buttrey',
    'Edward Buttrey': 'Ed Buttrey',
    'Hamlett, Bradley': 'Bradley Hamlett',
    'Moore, Frederick': 'Eric Moore',
    'Moore, Frederick (Eric)': 'Eric Moore',
    'Frederick (Eric) Moore': 'Eric Moore',
    'Tschida, Brad': 'Brad Tschida',
    'Caferro, Mary': 'Mary Caferro',
    'Harvey, Derek': 'Derek Harvey',
    'Harvey, Derek J.': 'Derek Harvey',
    'Derek J Harvey': 'Derek Harvey',
    'Harvey, DerekJ.': 'Derek Harvey',
    'Moore, Terry': 'Terry Moore',
    'Usher, Barry': 'Barry Usher',
    'Curdy, Willis': 'Willis Curdy',
    'Hayman, Denise': 'Denise Hayman',
    'Morigeau, Shane': 'Shane Morigeau',
    'Morigeau, Shane A.': 'Shane Morigeau',
    'Shane A Morigeau': 'Shane Morigeau',
    'Morigeau, ShaneA.': 'Shane Morigeau',
    'Vinton, Sue': 'Sue Vinton',
    'Custer, Geraldine': 'Geraldine Custer',
    'Hertz, Greg': 'Greg Hertz',
    'Mortensen, Dale': 'Dale Mortensen',
    'Weatherwax, Marvin': 'Marvin Weatherwax',
    'DeVries, Greg': 'Greg DeVries',
    'Holmlund, Kenneth': 'Kenneth Holmlund',
    'Holmlund, Kenneth L.': 'Kenneth Holmlund',
    'Kenneth L Holmlund': 'Kenneth Holmlund',
    'Holmlund, KennethL.': 'Kenneth Holmlund',
    'Noland, Mark': 'Mark Noland',
    'Webb, Peggy': 'Peggy Webb',
    'Doane, Alan': 'Alan Doane',
    'Hopkins, Mike': 'Mike Hopkins',
    'Olsen, Andrea': 'Andrea Olsen',
    'Welch, Tom': 'Tom Welch',
    'Dooling, Julie': 'Julie Dooling',
    'Jones, Llew': 'Llew Jones',
    'Peppers, Rae': 'Rae Peppers',
    'White, Kerry': 'Kerry White',
    'Dudik, Kimberly': 'Kim Dudik',
    'Kimberly Dudik': 'Kim Dudik',
    'Karjala, Jessica': 'Jessica Karjala',
    'Perry, Zac': 'Zac Perry',
    'Windy Boy, Jonathan': 'Jonathan Windy Boy',
    'WindyBoy, Jonathan': 'Jonathan Windy Boy',
    'Dunn, David': 'David Dunn',
    'Kassmier, Joshua': 'Josh Kassmier',
    'Joshua Kassmier': 'Josh Kassmier',
    'Pierson, Gordon': 'Gordon Pierson',
    'Winter, Thomas': 'Tom Winter',
    'Thomas Winter': 'Tom Winter',
    'Dunwell, Mary Ann': 'Mary Ann Dunwell',
    'Dunwell, MaryAnn': 'Mary Ann Dunwell',
    'Keane, Jim': 'Jim Keane',
    'Pope, Christopher': 'Chris Pope',
    'Christopher Pope': 'Chris Pope',
    'Woods, Tom': 'Tom Woods',
    'Duram, Neil': 'Neil Duram',
    'Kelker, Kathy': 'Kathy Kelker',
    'Read, Joe': 'Joe Read',
    'Zolnikov, Daniel': 'Daniel Zolnikov',

    // New in 2021
    'Bertoglio, Marta': 'Marta Bertoglio',
    'Binkley, Michele': 'Michele Binkley',
    'Boldman, Ellie': 'Ellie Boldman',
    'Brewster, Larry': 'Larry Brewster',
    'Buckley, Alice': 'Alice Buckley',
    'Carlson, Jennifer': 'Jennifer Carlson',
    'Fielder, Paul': 'Paul Fielder',
    'Fox, Mike': 'Mike Fox',
    'France, Tom': 'Tom France',
    'Frazer, Gregory': 'Gregory Frazer',
    'Friedel, Chris': 'Chris Friedel',
    'Galloway, Steven': 'Steven Galloway',
    'Gillette, Jane': 'Jane Gillette',
    'Gist, Steve': 'Steve Gist',
    'Hawk, Donavon': 'Donavon Hawk',
    'Hill, Ed': 'Ed Hill',
    'Hinkle, Jedediah': 'Jedediah Hinkle',
    'Hinkle, Caleb': 'Caleb Hinkle',
    'Kerns, Scot': 'Scot Kerns',
    'Kortum, Kelly': 'Kelly Kortum',
    'Ler, Brandon': 'Brandon Ler',
    'Malone, Marty': 'Marty Malone',
    'Marshall, Ron': 'Ron Marshall',
    'McGillvray, Tom': 'Tom McGillvray',
    'Mitchell, Braxton': 'Braxton Mitchell',
    'Molnar, Brad': 'Brad Molnar',
    'Nave, Fiona': 'Fiona Nave',
    'ave, Fiona': 'Fiona Nave',
    'Novak, Sara': 'Sara Novak',
    'O\'Brien, Shannon': 'Shannon O\'Brien',
    'Shannon O': 'Shannon O\'Brien',
    'Patelis, Jimmy': 'Jimmy Patelis',
    'Phalen, Bob': 'Bob Phalen',
    'Putnam, Brian': 'Brian Putnam',
    'Regier, Amy': 'Amy Regier',
    'Reksten, Linda': "Linda Reksten",
    '<skip>, Linda': "Linda Reksten",
    'Schillinger, Jerry': "Jerry Schillinger",
    'Seekins-Crowe, Kerri': "Kerri Seekins-Crowe",
    'Kerri Seekins': "Kerri Seekins-Crowe",
    'Stafman, Ed': "Ed Stafman",
    'Stromswold, Mallerie': "Mallerie Stromswold",
    'Tenenbaum, Danny': "Danny Tenenbaum",
    'Thane, Mark': "Mark Thane",
    'Trebas, Jeremy': "Jeremy Trebas",
    'Walsh, Kenneth': "Kenneth Walsh",
    'Whitman, Kathy': 'Kathy Whitman',
    'Whiteman Pena, Rynalea': 'Rynalea Whiteman Pena',
    'WhitemanPena, Rynalea': 'Rynalea Whiteman Pena',
    'Zolnikov, Katie': 'Katie Zolnikov',

    // New in 2023
    'Brad Barker': 'Brad Barker',
    'Denise Baum': 'Denise Baum',
    'James Bergstrom': 'James Bergstrom',
    'Tony Brockman': 'Tony Brockman',
    'Bob Carter': 'Bob Carter',
    'Robert Carter': 'Bob Carter',
    'Carter, Robert': 'Bob Carter',
    'Carter, Bob': 'Bob Carter',
    'Lee Deming': 'Lee Deming',
    'Sherry Essmann': 'Sherry Essmann',
    'Jodee Etchart': 'Jodee Etchart',
    'Terry Falk': 'Terry Falk',
    'John Fitzpatrick': 'John Fitzpatrick',
    'Paul Green': 'Paul Green',
    'Lyn Hellegaard': 'Lyn Hellegaard',
    'Sj Howell': 'SJ Howell',
    'Jonathan Karlen': 'Jonathan Karlen',
    'Greg Kmetz': 'Greg Kmetz',
    'Jennifer Lynch': 'Jennifer Lynch',
    'Eric Matthews': 'Eric Matthews',
    'Russ Miner': 'Russ Miner',
    'Russel Miner': 'Russ Miner',
    'Miner, Russel': 'Russ Miner',
    'Nelly Nicol': 'Nelly Nicol',
    'icol, Nelly': 'Nelly Nicol',
    'George Nikolakakos': 'George Nikolakakos',
    'Greg Oblander': 'Greg Oblander',
    'Gary Parry': 'Gary Parry',
    'Melissa Romano': 'Melissa Romano',
    'Wayne Rusk': 'Wayne Rusk',
    'Laura Smith': 'Laura Smith',
    'Tanner Smith': 'Tanner Smith',
    'Courtenay Sprunger': 'Courtenay Sprunger',
    'Paul Tuss': 'Paul Tuss',
    'Mike Yakawich': 'Mike Yakawich',
    'Michael Yakawich': 'Mike Yakawich',
    'Zooey Zephyr': 'Zooey Zephyr',
    'Daniel Emrich': 'Daniel Emrich',
    'Emrich, Daniel': 'Daniel Emrich',
    'Tom Mcgillvray': 'Tom McGillvray',
    'Wendy Mckamey': 'Wendy McKamey',
    'Shelley Vance': 'Shelley Vance',
    'Vance, Shelley': 'Shelley Vance',
    'Terry Vermeire': 'Terry Vermeire',
    'Vermeire, Terry': 'Terry Vermeire',
    'Zack Wirth': 'Zack Wirth',
    'Kmetz, Greg': 'Greg Kmetz',
    'Romano, Melissa': 'Melissa Romano',
    'Fitzpatrick, John': 'John Fitzpatrick',
    'Barker, Brad': 'Brad Barker',
    'Flament, Doug': 'Doug Flament',
    'Doug Flament': 'Doug Flament',
    'Flament, Douglas': 'Doug Flament',
    'Rusk, Wayne': 'Wayne Rusk',
    'Baum, Denise': 'Denise Baum',
    'Bergstrom, James': 'James Bergstrom',
    'Lynch, Jennifer': 'Jennifer Lynch',
    'Smith, Tanner': 'Tanner Smith',
    'Green, Paul': 'Paul Green',
    'Smith, Laura': 'Laura Smith',
    'Sprunger, Courtenay': 'Courtenay Sprunger',
    'Brockman, Tony': 'Tony Brockman',
    'Matthews, Eric': 'Eric Matthews',
    'Hellegaard, Lyn': 'Lyn Hellegaard',
    'Tuss, Paul': 'Paul Tuss',
    'Nicol, Nelly': 'Nelly Nicol',
    'Deming, Lee': 'Lee Deming',
    'Howell, SJ': 'SJ Howell',
    'Nikolakakos, George': 'George Nikolakakos',
    'Oblander, Greg': 'Greg Oblander',
    'Karlen, Jonathan': 'Jonathan Karlen',
    'Parry, Gary': 'Gary Parry',
    'Essmann, Sherry': 'Sherry Essmann',
    'Etchart, Jodee': 'Jodee Etchart',
    'Wirth, Zack': 'Zack Wirth',
    'Falk, Terry': 'Terry Falk',
    'Yakawich, Michael': 'Mike Yakawich',
    'Michael Yakawich': 'Mike Yakawich',
    'Zephyr, Zooey': 'Zooey Zephyr',
    'Ed Butcher': 'Ed Butcher',
    'Butcher, Ed': 'Ed Butcher',
    'Edward Butcher': 'Ed Butcher',
    'Edward B Butcher': 'Ed Butcher',
    'Butcher, Edward': 'Ed Butcher',
    'Naarah Hastings': 'Naarah Hastings',
    'Hastings, Naarah': 'Naarah Hastings',

    // 2025
    'Eric Albus': 'Eric Albus',
    'Lyn Bennett': 'Lyn Bennett',
    'Ed Byrne': 'Ed Byrne',
    'Brian Close': 'Brian Close',
    'Curtis Cochran': 'Curtis Cochran',
    'Thedis Crowe': 'Thedis Crowe',
    'Melody Cunningham': 'Melody Cunningham',
    'Julie Darling': 'Julie Darling',
    'Scott DeMarois': 'Scott DeMarois',
    'Becky Edwards': 'Becky Edwards',
    'Pete Elverum': 'Pete Elverum',
    'Sidney Fitzpatrick': 'Sidney Fitzpatrick',
    'Chip Fitzpatrick': 'Sidney Fitzpatrick',
    'Shelly Fyant': 'Shelly Fyant',
    'Bruce "Butch" Gillespie': 'Bruce Gillespie',
    'Bruce Gillespie': 'Bruce Gillespie',
    'Randyn Gregg': 'Randyn Gregg',
    'Alanah Griffith': 'Alanah Griffith',
    'Gregg Hunter': 'Gregg Hunter',
    'Jamie Isaly': 'Jamie Isaly',
    'Denise Joy': 'Denise Joy',
    'Steven Kelly': 'Steven Kelly',
    'Shane Klakken': 'Shane Klakken',
    'Gayle Lammers': 'Gayle Lammers',
    'Gayle  Lammers': 'Gayle Lammers',
    'Marc Lee': 'Marc Lee',
    'Kathy Love': 'Kathy Love',
    'Shannon Maness': 'Shannon Maness',
    'Tom Millett': 'Tom Millett',
    'Valerie Moore': 'Valerie Moore',
    'Jacinda Morigeau': 'Jacinda Morigeau',
    'Luke Muszkiewicz': 'Luke Muszkiewicz',
    'Cora Neumann': 'Cora Neumann',
    'Anthony Nicastro': 'Anthony Nicastro',
    'Melissa Nikolakakos': 'Melissa Nikolakakos',
    'Greg Overstreet': 'Greg Overstreet',
    'Chris Pope': 'Chris Pope',
    'Debo Powers': 'Debo Powers',
    'James Reavis': 'James Reavis',
    'Scott Rosenzweig': 'Scott Rosenzweig',
    'Curtis Schomer': 'Curtis Schomer',
    'Lukas Schubert': 'Lukas Schubert',
    'Joshua Seckinger': 'Joshua Seckinger',
    'Tracy Sharp': 'Tracy Sharp',
    'Jade Sooktis': 'Jade Sooktis',
    'Peter Strand': 'Peter Strand',
    'Tony Tezak': 'Tony Tezak',
    'Morgan Thiel': 'Morgan Thiel',
    'Eric Tilleman': 'Eric Tilleman',
    'Mike Vinton': 'Mike Vinton',
    'Ken Walsh': 'Ken Walsh',
    'Jane Weber': 'Jane Weber',
    'Terry Nelson': 'Terry Nelson'
};