name: Run Python Scripts on Schedule

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/20 12-23,0-6 * * *'
    # - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Restore Python dependencies cache
    - name: Restore Python dependencies cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-cache-

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Network diagnostics
      run: |
        echo "== DNS Lookup =="
        nslookup api.legmt.gov
        
        echo "== Checking connectivity =="
        curl -v -I https://api.legmt.gov 2>&1
        
        echo "== Runner IP Info =="
        curl -s https://ipinfo.io
        
        echo "== Traceroute =="
        traceroute api.legmt.gov

    # Ensure the script is executable
    - name: Make execute.sh executable
      run: chmod +x ./execute.sh

    # Execute the shell script
    - name: Run the shell script
      run: ./execute.sh

    # Save Python dependencies cache
    - name: Save Python dependencies cache
      if: always()
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('requirements.txt') }}

    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
