name: Run Python Scripts on Schedule

on:
  push:  # Trigger workflow on any push to the repository
    branches:
      - main  # Run only when pushing to the `main` branch
  schedule:
# runs every 20 mins
    - cron: '*/20 * * * *'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Cache Python dependencies to avoid reinstalling them each time
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-cache-
        save-always: true

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ensure that script is executable
    - name: Make execute.sh executable
      run: chmod +x ./execute.sh

    # Execute the shell script
    - name: Run the shell script
      run: ./execute.sh