name: Test Schedule on fix-404s

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    # First checkout main (where workflow file exists)
    - name: Checkout code
      uses: actions/checkout@v2

    # Switch to fix-404s branch
    - name: Switch to fix-404s branch
      run: |
        git fetch origin fix-404s
        git checkout fix-404s
        git pull origin fix-404s

    # Rest of your steps remain the same
    - name: Restore Python dependencies cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-cache-

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ensure the script is executable
    - name: Make execute.sh executable
      run: chmod +x ./execute.sh

    # Execute the shell script
    - name: Run the shell script
      run: ./execute.sh

    # Save Python dependencies cache
    - name: Save Python dependencies cache
      if: always()
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('requirements.txt') }}

    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Test run: ${timestamp}" || exit 0
        git push